---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate-nginx-cache-config
  namespace: nvr
  labels:
    app: frigate-nginx-cache-config
data:
  proxy.conf: |
    send_timeout 1800;
    client_body_timeout 5s;
    client_header_timeout 5s;
    access_log /dev/stdout;
    error_log /dev/stdout info;

    server {
      listen 80;
      client_max_body_size 64m;
      sendfile on;
      tcp_nodelay on;
      tcp_nopush on;

      location /thumbnail/ {
        proxy_pass http://frigate:5000/api/events/;

      }

      location ~* ^/clips/.*\.(mp4)$ {
        proxy_pass http://frigate:5000;

      }

    }