---
apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant
  namespace: home-assistant
  labels:
    app: home-assistant
data:
  automations.yaml: |-
    - id: '1613353187546'
      alias: Driveway Motion Light On
      description: Turn Driveway Ring Floodlight on when any motion is detected and the
        sun is down
      trigger:
      - platform: mqtt
        topic: frigate/events
      condition:
      - condition: and
        conditions:
        - condition: state
          entity_id: sun.sun
          state: below_horizon
        - condition: or
          conditions:
          - condition: template
            value_template: '{{ "alley" in trigger.payload_json["before"]["camera"] }}'
          - condition: template
            value_template: '{{ "frontporch" in trigger.payload_json["before"]["camera"]
              }}'
          - condition: template
            value_template: '{{ "frontyard" in trigger.payload_json["before"]["camera"]
              }}'
      action:
      - service: timer.start
        data:
          entity_id: timer.timer_frontyard_floodlight
      - type: turn_on
        device_id: 5d72ecc73b5e0be9c42de10be43be0fa
        entity_id: light.driveway_light
        domain: light
      mode: single
    - id: '1613432564617'
      alias: Person Detection at Daytime
      description: Alert me when a person is in certain zones throughout the day time.
      trigger:
      - platform: mqtt
        topic: frigate/events
      condition:
      - condition: and
        conditions:
        - condition: template
          value_template: '{{ trigger.payload_json["after"]["label"] == "person" }}'
        - condition: template
          value_template: '{{ is_state("timer.timer_daytime_person_cooldown", "idle")
            }}'
        - condition: template
          value_template: '{{ is_state("timer.timer_snooze_automations", "idle") }}'
        - condition: state
          entity_id: sun.sun
          state: above_horizon
        - condition: or
          conditions:
          - condition: template
            value_template: '{{ "Puppy Chair" in trigger.payload_json["after"]["current_zones"]
              }}'
          - condition: template
            value_template: '{{ "Front Patio" in trigger.payload_json["after"]["current_zones"]
              }}'
          - condition: template
            value_template: '{{ "Driveway" in trigger.payload_json["after"]["current_zones"]
              }}'
          - condition: template
            value_template: '{{ "Front Yard" in trigger.payload_json["after"]["current_zones"]
              }}'
          - condition: template
            value_template: '{{ "Alley" in trigger.payload_json["after"]["current_zones"]
              }}'
          - condition: template
            value_template: '{{ "Backyard" in trigger.payload_json["after"]["current_zones"]
              }}'
          - condition: template
            value_template: '{{ "Puppy Deck" in trigger.payload_json["after"]["current_zones"]
              }}'
          - condition: template
            value_template: '{{ "Puppy Area" in trigger.payload_json["after"]["current_zones"]
              }}'
          - condition: template
            value_template: '{{ "Garage" in trigger.payload_json["after"]["current_zones"]
              }}'
      action:
      - service: timer.start
        data:
          entity_id: timer.timer_daytime_person_cooldown
      - service: notify.mobile_app_pixel_4_xl
        data_template:
          message: "A {{trigger.payload_json[\"after\"][\"label\"]}} was detected by {{\n\
            \        trigger.payload_json[\"after\"][\"current_zones\"]|last }}.\n"
          data:
            ttl: 0
            priority: high
            image: https://frigate.home.jeffbeagley.com/api/events/{{trigger.payload_json["after"]["id"]}}/thumbnail.jpg
            clickAction: https://frigate.home.jeffbeagley.com/cameras/{{trigger.payload_json["after"]["camera"]}}?bbox=1&motion=1
            actions:
            - action: URI
              title: Open Camera
              uri: https://frigate.home.jeffbeagley.com/cameras/{{trigger.payload_json["after"]["camera"]}}?bbox=1&motion=1
      - service: notify.alexa_media
        data:
          message: "A {{trigger.payload_json[\"after\"][\"label\"]}} was detected by {{\n\
            \        trigger.payload_json[\"after\"][\"current_zones\"]|last }}."
          data:
            type: announce
            method: speak
          target:
          - media_player.kitchen
          - media_player.bathroom
          - media_player.bedroom
          - media_player.bedroom_echo
      mode: single
    - id: '1613447536410'
      alias: Puppy Deck Motion Light On
      description: Turn Puppy Deck Ring Floodlight on when any motion is detected and
        the sun is down
      trigger:
      - platform: mqtt
        topic: frigate/events
      condition:
      - condition: and
        conditions:
        - condition: state
          entity_id: sun.sun
          state: below_horizon
        - condition: or
          conditions:
          - condition: template
            value_template: '{{ "backyard" in trigger.payload_json["before"]["camera"]
              }}'
          - condition: template
            value_template: '{{ "puppydeck" in trigger.payload_json["before"]["camera"]
              }}'
          - condition: template
            value_template: '{{ "frontporch" in trigger.payload_json["before"]["camera"]
              }}'
          - condition: template
            value_template: '{{ "alley" in trigger.payload_json["before"]["camera"] }}'
      action:
      - service: timer.start
        data:
          entity_id: timer.timer_puppydeck_floodlight
      - type: turn_on
        device_id: 74f02a570b63a2474ab8184c74cffa00
        entity_id: light.puppy_deck_light
        domain: light
      mode: single
    - id: '1613447968393'
      alias: Puppy Deck Motion Light Off
      description: ''
      trigger:
      - platform: state
        entity_id: timer.timer_puppydeck_floodlight
        from: active
        to: idle
      condition: []
      action:
      - type: turn_off
        device_id: 74f02a570b63a2474ab8184c74cffa00
        entity_id: light.puppy_deck_light
        domain: light
      mode: single
    - id: '1613448023644'
      alias: Driveway Motion Light Off
      description: ''
      trigger:
      - platform: state
        entity_id: timer.timer_frontyard_floodlight
        from: active
        to: idle
      condition: []
      action:
      - type: turn_off
        device_id: 5d72ecc73b5e0be9c42de10be43be0fa
        entity_id: light.driveway_light
        domain: light
      mode: single
    - id: '1613448448886'
      alias: Person Detection at Night
      description: 'Alert Devices when person detection is at night '
      trigger:
      - platform: mqtt
        topic: frigate/events
      condition:
      - condition: and
        conditions:
        - condition: template
          value_template: '{{ trigger.payload_json["after"]["label"] == "person" }}'
        - condition: template
          value_template: '{{ is_state("timer.timer_nighttime_person_cooldown", "idle")
            }}'
        - condition: state
          entity_id: sun.sun
          state: below_horizon
      action:
      - service: timer.start
        data:
          entity_id: timer.timer_nighttime_person_cooldown
      - service: notify.mobile_app_pixel_4_xl
        data_template:
          message: 'A {{trigger.payload_json["after"]["label"]}} was detected by {{

            trigger.payload_json["after"]["current_zones"]|last }}.,

            '
          data:
            ttl: 0
            priority: high
            image: https://frigate.home.jeffbeagley.com/api/events/{{trigger.payload_json["after"]["id"]}}/thumbnail.jpg
            clickAction: https://frigate.home.jeffbeagley.com/cameras/{{trigger.payload_json["after"]["camera"]}}?bbox=1&motion=1
            actions:
            - action: URI
              title: Open Camera
              uri: https://frigate.home.jeffbeagley.com/cameras/{{trigger.payload_json["after"]["camera"]}}?bbox=1&motion=1
      - service: notify.alexa_media
        data:
          message: A {{trigger.payload_json["after"]["label"]}} was detected by {{ trigger.payload_json["after"]["current_zones"]|last
            }}.,
          data:
            type: announce
            method: speak
          target:
          - media_player.kitchen
          - media_player.bathroom
          - media_player.bedroom
          - media_player.bedroom_echo
      mode: single
    - id: '1613541091917'
      alias: Puppy Deck Motion Light On NEW
      description: Turn Puppy Deck Ring Floodlight on when any motion is detected and
        the sun is down
      trigger:
      - platform: template
        value_template: '{{ states(''sensor.backyard_detection_fps'')|float > 0 }}'
      - platform: template
        value_template: '{{ states(''sensor.puppydeck_detection_fps'')|float > 0 }}'
      - platform: template
        value_template: '{{ states(''sensor.alley_detection_fps'')|float > 0 }}'
      - platform: template
        value_template: '{{ states(''sensor.kitchen_detection_fps'')|float > 0 }}'
      condition:
      - condition: and
        conditions:
        - condition: state
          entity_id: sun.sun
          state: below_horizon
      action:
      - type: turn_on
        device_id: 74f02a570b63a2474ab8184c74cffa00
        entity_id: light.puppy_deck_light
        domain: light
      - service: timer.start
        data:
          entity_id: timer.timer_puppydeck_floodlight
      mode: single
    - id: '1614563694013'
      alias: Night Time Lighting On
      description: Turn on and configure any exterior light when the sun sets
      trigger:
      - platform: state
        entity_id: sun.sun
        to: below_horizon
      condition: []
      action:
      - type: turn_on
        device_id: 002439fad9ac4db3d16c3f122b370367
        entity_id: light.front_patio
        domain: light
        brightness_pct: 10
      mode: single
    - id: '1614563768337'
      alias: Night Time Lighting Off
      description: Turn off lights when the sun rises
      trigger:
      - platform: state
        entity_id: sun.sun
        to: above_horizon
      condition: []
      action:
      - type: turn_off
        device_id: 002439fad9ac4db3d16c3f122b370367
        entity_id: light.front_patio
        domain: light
      mode: single
    - id: '1614564585758'
      alias: Person Detection at Night Front Patio Lights
      description: Turn front Patio Lights to 100% when detected motion in front yard
        at night
      trigger:
      - platform: mqtt
        topic: frigate/events
      condition:
      - condition: and
        conditions:
        - condition: state
          entity_id: sun.sun
          state: below_horizon
        - condition: template
          value_template: '{{ trigger.payload_json["after"]["label"] == "person" }}'
        - condition: or
          conditions:
          - condition: template
            value_template: '{{ "Front Yard" in trigger.payload_json["after"]["current_zones"]
              }}'
          - condition: template
            value_template: '{{ "Driveway" in trigger.payload_json["after"]["current_zones"]
              }}'
      action:
      - service: timer.start
        data: {}
        entity_id: timer.timer_nighttime_person_frontpatio_cooldown
      - type: turn_on
        device_id: 002439fad9ac4db3d16c3f122b370367
        entity_id: light.front_patio
        domain: light
        brightness_pct: 100
      mode: single
    - id: '1614565112086'
      alias: Front Patio Motion Lights off
      description: Turn down front patio lights to normal 10% when no more motion is detected
      trigger:
      - platform: state
        entity_id: timer.timer_nighttime_person_frontpatio_cooldown
        from: active
        to: idle
      condition: []
      action:
      - type: turn_on
        device_id: 002439fad9ac4db3d16c3f122b370367
        entity_id: light.front_patio
        domain: light
        brightness_pct: 10
      mode: single
    - id: '1616041218254'
      alias: test_phone_notification
      description: ''
      trigger:
      - platform: mqtt
        topic: frigate/events
      condition:
      - condition: and
        conditions:
        - condition: template
          value_template: '{{ is_state("timer.timer_nighttime_person_cooldown", "idle")}}'
      action:
      - service: notify.mobile_app_pixel_4_xl
        data_template:
          message: 'Test Notification

            '
          data:
            ttl: 0
            priority: high
            clickAction: https://frigate.home.jeffbeagley.com/cameras/
            actions:
            - action: URI
              title: Open Camera
              uri: https://frigate.home.jeffbeagley.com/cameras/
            - action: silence
              title: Snooze
      mode: single
    - id: '1616043009297'
      alias: Snooze_Automations
      description: Snooze Automations based on specific Input Toggles that define the
        duration
      trigger:
      - platform: state
        entity_id: input_select.snooze_time_select
      condition:
      - condition: template
        value_template: '{{ not is_state(''input_select.snooze_time_select'', ''Off'')
          }}'
      action:
      - service: timer.start
        data:
          entity_id: timer.timer_snooze_automations
          duration: 00:{{ states('input_select.snooze_time_select') }}:00
      mode: single
    - id: '1616044592774'
      alias: Disable Snooze
      description: ''
      trigger:
      - platform: state
        entity_id: input_select.snooze_time_select
      condition:
      - condition: template
        value_template: '{{ is_state(''input_select.snooze_time_select'', ''Off'') }}'
      action:
      - service: timer.finish
        entity_id: timer.timer_snooze_automations
      mode: single

  configuration.yaml: |-
    # Configure a default setup of Home Assistant (frontend, api, etc)
    default_config:

    # Text to speech
    tts:
      - platform: google_translate

    group: !include groups.yaml
    automation: !include automations.yaml
    script: !include scripts.yaml
    scene: !include scenes.yaml

    wemo:
      discovery: false
      static:
        - 192.168.1.143
        - 192.168.1.142
        - 192.168.1.42
        - 192.168.1.105
    panel_iframe:
      router:
        title: "Frigate"
        url: "https://frigate.home.jeffbeagley.com"
    input_select:
        snooze_time_select:
          name: Snooze Automations
          options:
            - "Off"
            - "30"
            - "60"
            - "90"
            - "180"
          icon: mdi:timer
    camera:
      - platform: generic
        name: Front Porch
        still_image_url: "http://172.16.7.13/snap.jpeg"
        stream_source: "rtsp://172.16.7.9:7447/bGvgQ7tbtP2lc3QG"

  
