---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate-config
  namespace: nvr
  labels:
    app: frigate
data:
  config.yml: |-
    detectors:
      cpu1:
        type: cpu
      cpu2:
        type: cpu
      cpu3:
        type: cpu
      cpu4:
        type: cpu
    mqtt:
      # Required: host name
      host: mqtt-svc
      # Optional: port (default: shown below)
      port: 1883
      # Optional: topic prefix (default: shown below)
      # WARNING: must be unique if you are running multiple instances
      topic_prefix: frigate
      # Optional: client id (default: shown below)
      # WARNING: must be unique if you are running multiple instances
      client_id: frigate
      # Optional: user
      #user: mqtt_user
      # Optional: password
      # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}.
      #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
      password: password
      # Optional: interval in seconds for publishing stats (default: shown below)
      #stats_interval: 60
    objects:
      track:
        - person
        - vehicle
        - animal
      filters:
        person:
          min_area: 2000
          max_area: 100000
          threshold: 0.75
    clips:
      max_seconds: 600
      retain:
        default: 7
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      input_args: >-
        -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport
        tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
      output_args:
        detect: '-f rawvideo -pix_fmt yuv420p'
        record: >-
          -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1
          -strftime 1 -c copy
        clips: >-
          -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1
          -strftime 1 -c copy
    cameras:
      frontporch:
        ffmpeg:
          inputs:
            - path: rtsp://172.16.7.9:7447/wkBxF2rsJSeUd0F8
              roles:
                - detect
                - clips
        width: 1280
        height: 720
        fps: 15
        clips:
          enabled: true
          pre_capture: 2
          post_capture: 15
        snapshots:
          enabled: true
          timestamp: false
          bounding_box: true
          retain:
            default: 30
        zones:
          "Front Patio":
            coordinates: 0,720,1280,720,1280,440,814,331,248,602
            filters:
              person:
                min_area: 500
                max_area: 100000
                threshold: 0.7
          Driveway:
            coordinates: 1280,175,694,149,415,257,1280,425
          "Eds Yard":
            coordinates: 1240,169,1223,32,1023,67,776,143
            filters:
              person:
                min_area: 5000
                max_area: 100000
                threshold: 0.7
          Street:
            coordinates: 0,236,665,54,941,0,1245,0,0,374
            filters:
              vehicle:
                min_area: 1000
                max_area: 100000
                threshold: 0.6
              person:
                min_area: 500
                max_area: 100000
                threshold: 0.3
          "Front Yard":
            coordinates: 176,351,406,270,838,335,279,604
            filters:
              person:
                min_area: 500
                max_area: 100000
                threshold: 0.6
        motion:
          mask:
            - 367,29,373,120,210,141,211,208,184,200,88,104
      frontyard:
        ffmpeg:
          inputs:
            - path: rtsp://172.16.7.9:7447/QJknjUjZxlnVgr9q
              roles:
                - detect
                - clips
        width: 1920
        height: 1080
        fps: 15
        clips:
          enabled: true
          pre_capture: 2
          post_capture: 15
        snapshots:
          enabled: true
          timestamp: false
          bounding_box: true
          retain:
            default: 30
        zones:
          "Front Yard":
            coordinates: 0,1080,834,311,1357,267,1920,257,1920,1080
            filters:
              person:
                min_area: 500
                max_area: 100000
                threshold: 0.7
          "Kellie and Chris's Yard":
            coordinates: 53,438,0,465,0,1080,884,303
          Street:
            coordinates: 1199,55,560,183,87,313,0,452,582,355,1251,266,1920,255,1920,41
            filters:
              vehicle:
                min_area: 1000
                max_area: 100000
                threshold: 0.5
              person:
                min_area: 500
                max_area: 100000
                threshold: 0.3
        motion:
          mask:
            - 0,0,1323,0,1920,0,1920,57,1138,94,502,198,0,363 ## tree line
        objects:
          filters:
            person:
              mask: 
                - 427,518,288,540,124,94,580,0,635,91,544,187,328,178
                - 855,166,841,70,798,81,815,160
                - 1289,0,1299,77,1266,84,1245,0
      alley:
        ffmpeg:
          inputs:
            - path: rtsp://172.16.7.9:7447/Jsmq7T6p0xJDJpiC
              roles:
                - detect
                - clips
        width: 640
        height: 360
        fps: 5
        clips:
          enabled: true
          pre_capture: 2
          post_capture: 15
        snapshots:
          enabled: true
          timestamp: false
          bounding_box: true
          retain:
            default: 30
        zones:
          Alley:
            coordinates: 640,360,0,360,0,163,0,0,640,0
      backyard:
        ffmpeg:
          inputs:
            - path: rtsp://172.16.7.9:7447/VU757vpltwJdOStJ
              roles:
                - detect
                - clips
        width: 640
        height: 360
        fps: 5
        clips:
          enabled: true
          pre_capture: 2
          post_capture: 15
        snapshots:
          enabled: true
          timestamp: false
          bounding_box: true
          retain:
            default: 30
        zones:
          Backyard:
            coordinates: 640,0,640,360,0,360,0,0
            filters:
              animal:
                min_area: 500
                max_area: 100000
                threshold: 0.5
              person:
                min_area: 500
                max_area: 100000
                threshold: 0.7
      puppydeck:
        ffmpeg:
          inputs:
            - path: rtsp://172.16.7.9:7447/gGFsUv20rPsoxL2M
              roles:
                - detect
                - clips
        width: 640
        height: 360
        fps: 15
        clips:
          enabled: true
          pre_capture: 2
          post_capture: 15
        snapshots:
          enabled: true
          timestamp: false
          bounding_box: true
          retain:
            default: 30
        zones:
          "Eds Backyard":
            coordinates: 169,110,370,0,0,0,0,223
          "Puppy Area":
            coordinates: 573,0,380,0,186,140,372,177,364,255,534,285
            filters:
              animal:
                min_area: 300
                max_area: 100000
                threshold: 0.5
              person:
                min_area: 300
                max_area: 100000
                threshold: 0.7
          "Puppy Deck":
            coordinates: 0,236,0,360,375,360,328,307,396,196,158,123
      garage:
        ffmpeg:
          inputs:
            - path: rtsp://172.16.7.9:7447/GxxGS0IQ39Cf6MhW
              roles:
                - detect
                - clips
        width: 640
        height: 360
        fps: 5
        clips:
          enabled: true
          pre_capture: 2
          post_capture: 15
        snapshots:
          enabled: true
          timestamp: false
          bounding_box: true
          retain:
            default: 30
        zones:
          Garage:
            coordinates: 0,360,0,0,640,0,640,360
      kitchen:
        ffmpeg:
          inputs:
            - path: rtsp://172.16.7.9:7447/dVex46f86wzMpiP4
              roles:
                - detect
                - clips
        width: 640
        height: 360
        fps: 5
        clips:
          enabled: true
          pre_capture: 2
          post_capture: 15
        snapshots:
          enabled: true
          timestamp: false
          bounding_box: true
          retain:
            default: 30
        zones:
          "Puppy Chair":
            coordinates: 304,42,332,72,310,360,46,314,34,312,24,52
  labelmap.txt: |
    0  person
    1  bicycle
    2  vehicle
    3  vehicle
    4  airplane
    5  vehicle
    6  train
    7  vehicle
    8  boat
    9  traffic light
    10  fire hydrant
    12  stop sign
    13  parking meter
    14  bench
    15  bird
    16  animal
    17  animal
    18  horse
    19  sheep
    20  cow
    21  elephant
    22  bear
    23  zebra
    24  giraffe
    26  backpack
    27  umbrella
    30  handbag
    31  tie
    32  suitcase
    33  frisbee
    34  skis
    35  snowboard
    36  sports ball
    37  kite
    38  baseball bat
    39  baseball glove
    40  skateboard
    41  surfboard
    42  tennis racket
    43  bottle
    45  wine glass
    46  cup
    47  fork
    48  knife
    49  spoon
    50  bowl
    51  banana
    52  apple
    53  sandwich
    54  orange
    55  broccoli
    56  carrot
    57  hot dog
    58  pizza
    59  donut
    60  cake
    61  chair
    62  couch
    63  potted plant
    64  bed
    66  dining table
    69  toilet
    71  tv
    72  laptop
    73  mouse
    74  remote
    75  keyboard
    76  cell phone
    77  microwave
    78  oven
    79  toaster
    80  sink
    81  refrigerator
    83  book
    84  clock
    85  vase
    86  scissors
    87  teddy bear
    88  hair drier
    89  toothbrush

