apiVersion: v1
kind: Service
metadata:
  name: frigate
  namespace: nvr
spec:
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
  selector:
    app: frigate
---
apiVersion: v1
kind: Service
metadata:
  name: frigate-rtmp
  namespace: nvr
spec:
  ports:
    - protocol: TCP
      port: 1935
      targetPort: 1935
  type: LoadBalancer
  selector:
    app: frigate
---
apiVersion: v1
kind: Service
metadata:
  name: frigate
  namespace: nvr
  labels:
    app: frigate
spec:
  ports:
    - port: 1935
      targetPort: 1935
      protocol: TCP
      name: rtmp
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: web
  type: NodePort
  selector:
    app: frigate
---
apiVersion: v1
kind: Service
metadata:
  name: frigate-rtmp-svc
  namespace: nvr
  labels:
    app: frigate
spec:
  ports:
    - port: 1935
      targetPort: 1935
      protocol: TCP
  type: NodePort
  selector:
    app: frigate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: frigate-pv-volume
  namespace: nvr
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/disks/frigate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - server-01
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-pv-claim
  namespace: nvr
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frigate
  namespace: nvr
  labels:
    app: frigate
spec:
  replicas: 1
  selector:
    matchLabels:
     app: frigate
  template:
    metadata:
      labels:
        app: frigate
    spec:
      volumes:
        - name: frigate-media-storage
          persistentVolumeClaim:
            claimName: frigate-pv-claim
        - name: frigate-config
          configMap:
            name: frigate-config
        - name: tmp-cache
          emptyDir: {}
      containers:
      - name: frigate
        image: blakeblackshear/frigate:0.8.2-amd64
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 4
            memory: 8Gi
            ephemeral-storage: "2Gi"
          requests:
            cpu: 500m
            memory: 3Gi
            ephemeral-storage: "1Gi"
        volumeMounts:
          - name: frigate-media-storage
            mountPath: /media
          - name: frigate-config 
            mountPath: /config/config.yml
            subPath: config.yml
          - name: frigate-config 
            mountPath: /labelmap.txt
            subPath: labelmap.txt
          - name: tmp-cache
            mountPath: /tmp/cache
        # Many applications running for long periods of time eventually transition to broken states, 
        # and cannot recover except by being restarted. Kubernetes provides liveness probes to detect 
        # and remedy such situations.
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 10
          # how often to perform this check
          periodSeconds: 10
        # Sometimes, applications are temporarily unable to serve traffic. For example, an application might 
        # need to load large data or configuration files during startup, or depend on external services after 
        # startup. In such cases, you don't want to kill the application, but you don't want to send it requests either
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 0
          # how often to perform this check
          periodSeconds: 5
