---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zigbee2mqtt-config
  namespace: nvr
  labels:
    app: zigbee2mqtt-config
data:
  configuration.yaml: |-
    # Home Assistant integration (MQTT discovery)
    homeassistant: false

    # allow new devices to join
    permit_join: true

    # MQTT settings
    mqtt:
      # MQTT base topic for zigbee2mqtt MQTT messages
      base_topic: zigbee2mqtt
      # MQTT server URL
      server: 'mqtt://mqtt-svc'
      port: 1883
      client_id: zigbee2mqtt
      # MQTT server authentication, uncomment if required:
      # user: my_user
      password: password

    # Serial settings
    serial:
      # Location of CC2531 USB sniffer
      port: /dev/ttyACM0
