---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zigbee-pv-volume
  namespace: nvr
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/disks/zigbee2mqtt
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - server-01
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zigbee-pv-claim
  namespace: nvr
spec:
  storageClassName: local-storage
  volumeName: zigbee-pv-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zigbee2mqtt
  namespace: nvr
  labels:
    app: zigbee2mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
     app: zigbee2mqtt
  template:
    metadata:
      labels:
        app: zigbee2mqtt
    spec:
      volumes:
        - name: zigbee2mqtt-data
          persistentVolumeClaim:
            claimName: zigbee-pv-claim
        - name: zigbee2mqtt-config
          configMap:
            name: zigbee2mqtt-config
        - name: adapter
          hostPath:
            path: /dev/ttyACM0
      containers:
      - name: zigbee2mqtt
        image: koenkk/zigbee2mqtt
        securityContext:
          privileged: true
        env:
        - name: TZ
          value: "America/Chicago"
        volumeMounts:
          - name: zigbee2mqtt-data
            mountPath: /app/data
          - name: zigbee2mqtt-config
            mountPath: /app/configuration.yaml
            subPath: configuration.yaml
          - name: adapter
            mountPath: /dev/ttyACM0
            


